import type { Metadata } from "next";
//import Metadata from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <nav className="text-center">
              <Link href="/">Home</Link>
              <Link href="/posts">Posts</Link>
              <Link href="/users">Users</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
